# Generated by Django 5.0.1 on 2024-01-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderapp', '0002_curso_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fechaDeEntrega', models.DateField()),
                ('entregado', models.BooleanField()),
            ],
        ),
    ]
